structured installer and added command entry to /bin

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -5,29 +5,80 @@ G="\033[0;32m"
 R="\033[0;31m"
 Y="\033[0;33m"
 
-printf "$W[$R*$W] Welcome to the Hunter-Toolkit!\n"
-sleep 1.25
+function permission_check() {
+	if [ "$(id -u)" != 0 ]; then
+		printf "$W[$Y-$W] installer failed, are you root?\n"
+		exit 1
+	else
+		printf "$W[$R*$W] Welcome to the Hunter-Toolkit!\n"
+		sleep 1.25
+	fi
+}
+
+function create_command() {
+	if touch /bin/htkit && echo -e "#!/bin/bash\n\npython3 $PWD/htkit" > /bin/htkit; then
+		printf "$W[$R*$W] created bin entry successfully\n"
+	else
+		printf "$W[$Y-$W] installer failed, implementation failed on bash file creation\n" 
+		exit 1
+	fi
+
+	if ! chmod +x /bin/htkit; then
+		printf "$W[$Y-$W] installer failed, cannot make htkit executable\n"
+                exit 1
+	else
+		printf "$W[$R*$W] chmod succeed\n"
+	fi
+
+	printf "$W[$G+$W] done\n"
+}
+
+function install_requirements() {
+	if ! command -v pip &> /dev/null; then
+        	sudo apt-get update && sudo apt-get install -y python3 python3-pip
+	fi
+
+	if [ -f "htkit/requirements.txt" ]; then
+        	if pip install -r htkit/requirements.txt &> /dev/null; then
+			printf "$W[$G+$W] requirements installed successfully\n"
+		else
+ 			printf "$W[$Y-$W] installer failed, cannot install the requirements\n" 
+			exit 1
+		fi
+	elif [ -f "requirements.txt" ]; then
+        	if pip install -r requirements.txt &> /dev/null; then 
+                        printf "$W[$G+$W] requirements installed successfully\n"
+                else
+                        printf "$W[$Y-$W] installer failed, cannot install the requirements\n" 
+                        exit 1
+		fi
+	fi
+
+	printf "$W[$G+$W] done\n"
+}
+
+# entry point
+
+permission_check
+
 printf "$W[$R*$W] Do you want to start the installer? y/n "
 read START
 
 if [[ $START == "y" || $START == "Y" ]]; then
-	printf "$W[$R*$W] Starting the installer ...\n"
-	sleep 1.25
+        printf "$W[$R*$W] Starting the installer ...\n"
+        sleep 1.25
 elif [[ $START == "n" || $START == "N" ]]; then
-	printf "$W[$R*$W] All right, thank you for choosing the Hunter-Toolkit!\n"
-	exit 0
+        printf "$W[$R*$W] All right, thank you for choosing the Hunter-Toolkit!\n"
+        exit 0
 else
-	printf "$W[$R*$W] Invalid input, try again!\n"
-	exit 1
+        printf "$W[$R*$W] Invalid input, try again!\n"
+        exit 1
 fi
 
-if ! command -v pip &> /dev/null; then
-        sudo apt-get update && sudo apt-get install python3 python3-pip 
-fi
-
-if [ -f "req/requirements.txt" ]; then
-        pip install -r req/requirements.txt
-fi
+printf "$W[$R*$W] installing the requirements ...\n"
+install_requirements
+printf "$W[$R*$W] create system command ...\n"
+create_command
 
 printf "$W[$G+$W] Hunter-Toolkit is now ready to use ...\n"
 sleep 1.25
@@ -35,15 +86,15 @@ printf "$W[$R*$W] Do you want to start the Hunter-Toolkit? y/n "
 read CHOICE
 
 if [[ $CHOICE == "y" || $CHOICE == "Y" ]]; then
-	printf "$W[$R*$W] Starting the Hunter-Toolkit ...\n"
-	sleep 1.25
-	python3 htkit
-	exit 0
+        printf "$W[$R*$W] Starting the Hunter-Toolkit ...\n"
+        sleep 1.25
+        htkit
+        exit 0
 elif [[ $CHOICE == "n" || $CHOICE == "N" ]]; then
-	printf "$W[$R*$W] All right, thank you for choosing the Hunter-Toolkit!\n"
-	exit 0
+        printf "$W[$R*$W] All right, thank you for choosing the Hunter-Toolkit!\n"
+        exit 0
 else
-	printf "$W[$Y-$W] Invalid Input!\n"
-	exit 1
+        printf "$W[$Y-$W] Invalid Input!\n"
+        exit 1
 fi
 
